### PR TITLE
Support Nuxt

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@melloware don't you think so we should upgrade java 11 to 17 for this project if this is , would you like to share process?

**Comment by melloware** [comment]
Let me ask on the mailing list whether any other extensions are moving to 17.

**Comment by melloware** [comment]
"Except if you have a very strong reason to use 17, we recommend using 11 as long as Quarkus itself supports 11. "

**Comment by shivam-sharma7** [comment]
@melloware You know migration is like migrain which we have to do according to time and we also want our project use letest tech stack right I don't think JDK 11 going to support for long time.

@ia3andy WDYT?

**Pull request merged**
