### PR TITLE
Plus sign look better in dark/light theme

### PR DESCRIPTION
**Pull request by melloware**
This makes the + sign on the ReadME look better in both light and dark theme

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@melloware why build is failing?

**Comment by shivam-sharma7** [comment]
> @melloware why build is failing? I think you should try `npm install` then force push

**Comment by melloware** [comment]
I have no idea why it's failing?

**Comment by shivam-sharma7** [comment]
Np, this is docs related changes so we can skip this

**Review by shivam-sharma7 — APPROVED** [review]
LGTM 👌

**Comment by ia3andy** [comment]
I've restarted the CI

**Review by ia3andy — APPROVED** [review]
Thanks!

**Pull request merged**
