### PR TITLE
Fix #682: Allow to define if dev-server is HTTPS / TLS

### LINKED ISSUE #682: Allow to define if dev-server is HTTPS / TLS
## Feature idea
Currently, dev-server host and port are configurable.
But not the protocol. Please add support for https.

## Additional information
With the current situation :
If quarkus is used in https and angular is in http, the webapp will try to connect to `wss://host/ng-cli-ws` (and fail because ng serve is configured in http).
If quarkus is used in https and angular is in https, quinoa dev-server won't work.

### PR DESCRIPTION
**Pull request by ylemoigne**
Fix #682: Allow to define if dev-server is HTTPS / TLS

This PR add support for HTTPS/TLS for dev-server.

It's my first PR on quarkus and quinoa so if I missed some standard/convention and need rework, tell me (or do the change).

Thanks.

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
looks like formatter failed can you run `mvn -f deployment net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format` to format the code and commit

**Comment by ylemoigne** [comment]
Hello Melloware. I've launched the formatter.

**Comment by melloware** [comment]
OK nice it looks like build is passing now!

**Comment by ia3andy** [comment]
I will have a look today.. thanks!

**Review by ia3andy — APPROVED** [review]
Code looks good, I haven't tested though

@melloware  We could move the devmode (including ForwardedDevModeProcessor) stuff to a specific package

**Comment by melloware** [comment]
@ia3andy agreed we could move that stuff to a ".devmode" package?  I will do that after I merge this PR.

**Comment by melloware** [comment]
I am going to merge this and make this part of 2.3.8 so I can start a new 2.4.0 branch for Quarkus 3.12

**Pull request merged**
