### PR TITLE
Refactor: `NuxtFramework`

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@melloware please give a titile for PR

**Comment by melloware** [comment]
Title looks good, Nice PR.

**Review by ia3andy — CHANGES_REQUESTED** [review]
Coould you use the NextFramework class that you copied (instead of duplicating), and just edit the build dir, if it's really a different one.

@melloware did you check it works?

**Comment by shivam-sharma7** [comment]
@ia3andy I don't understand your piont, next and nuxt both are different

**Comment by ia3andy** [comment]
@shivam-sharma7 
Have a look to this file: https://github.com/quarkiverse/quarkus-quinoa/blob/478fcac129cdc00dc7525a2e381b4c8626f053e7/deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NuxtFramework.java

Then this file:
https://github.com/quarkiverse/quarkus-quinoa/blob/478fcac129cdc00dc7525a2e381b4c8626f053e7/deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java

**Comment by melloware** [comment]
I am not familiar with Nuxt but I assume its different than Next?

**Comment by ia3andy** [comment]
> I am not familiar with Nuxt but I assume its different than Next?

It's a different framework, but the logic for detection seems to be similar

**Comment by ia3andy** [comment]
At least from the PR code, I am not familiar with either.

**Comment by melloware** [comment]
Oh i see what you are saying its so similar to Next should we refactor these two to be similar and just override the `script` its looking for?

**Comment by ia3andy** [comment]
> Oh i see what you are saying its so similar to Next should we refactor these two to be similar and just override the `script` its looking for?

yes and the build dir needs to be checked

**Comment by shivam-sharma7** [comment]
> > Oh i see what you are saying its so similar to Next should we refactor these two to be similar and just override the `script` its looking for?
> 
> yes and the build dir needs to be checked

we don't need export like next in nuxt so we can check build `script`
see https://github.com/quarkiverse/quarkus-quinoa/blob/478fcac129cdc00dc7525a2e381b4c8626f053e7/deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java#L28

my current change is
```java
if (scripts.getString("build") == null) {
```

**Comment by ia3andy** [comment]
From what you are saying, it looks to me that Nuxt is a regular (generic) framework. @melloware could you have a look?

**Comment by melloware** [comment]
@shivam-sharma7 I don't understand what with Nuxt is NOT working with the current code?

```java
NUXT(Set.of("nuxt dev"), generic("dist", "dev", 3000)),
```

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 I don't understand what with Nuxt is NOT working with the current code?
> 
> ```java
> NUXT(Set.of("nuxt dev"), generic("dist", "dev", 3000)),
> ```

@melloware Test with my current branch

**Comment by melloware** [comment]
@shivam-sharma7 Using the current 2.2.1 plugin Nuxt works out of the box.

Attached zip: 
[nuxt.zip](https://github.com/quarkiverse/quarkus-quinoa/files/13166902/nuxt.zip)

Run `mvn quarkus:dev` and navigate to https://localhost:8080 its working fine?

**Comment by ia3andy** [comment]
Something you can do though is print some Warning if no "build" is found on the GenericFramework.

**Pull request closed without merging**
