### PR TITLE
2.0.7

### PR DESCRIPTION
**Pull request by melloware**
2.0.8 release as the 2.0.7 failed

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@melloware should we wait for @ia3andy or should I raise this same PR so that you can approve and megred.

**Comment by melloware** [comment]
I think we need to wait because I wonder if it failed because you are not a member of this team so it won't allow your user to do releases. So I think it has to be my or Andy's user

**Comment by shivam-sharma7** [comment]
because you are not a member of this team so it won't allow your user to do releases.  

💔

**Comment by melloware** [comment]
@gastaldi do you mind approving this so I can merge it?

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Releases should only be performed from a branch coming from the same repository. Forks won't work

**Comment by gastaldi** [comment]
@melloware I'd suggest to revert the previous commit and release 2.0.7 here

**Comment by shivam-sharma7** [comment]
> @melloware I'd suggest to revert the previous commit (push directly to main) and release 2.0.7 here

I agree with @gastaldi idea

**Comment by melloware** [comment]
Done the new release is 2.0.7 happening now

**Comment by shivam-sharma7** [comment]
@melloware see this- https://github.com/quarkiverse/quarkus-quinoa/actions/runs/5563230002/jobs/10162052436#step:10:9

**Comment by gastaldi** [comment]
The release workflow does not support protected branches, that needs to be disabled for now

**Comment by shivam-sharma7** [comment]
> The release workflow does not support protected branches, that needs to be disabled for now

open a PR for this

**Comment by gastaldi** [comment]
Branch protection rules removed. @melloware can you please tag locally and push the 2.0.7 tag? Releasing 2.0.7 again won't work because it's already deployed in central

**Comment by shivam-sharma7** [comment]
Done https://github.com/quarkiverse/quarkus-quinoa/releases/tag/2.0.7

**Comment by ia3andy** [comment]
@shivam-sharma7 @melloware sorry guys I was busy on a conference last week. It seems you figured things out :)

**Comment by gastaldi** [comment]
@shivam-sharma7 I created https://github.com/quarkiverse/quarkiverse-devops/pull/165 asking ti include you as a team member 😉

**Comment by shivam-sharma7** [comment]
Thanks team.

**Pull request merged**
