### PR TITLE
check maven version before build

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by shivam-sharma7** [comment]
@melloware Would you like a video meet? where you told me how to get started with quinoa, a basic react project setup using quinoa. we can do this today or on weekend if you agree then.

Thanks :)

**Comment by melloware** [comment]
I already have a full React example here including Rest services, Postgres DB, React Query , Quinoa etc.

You need JDK17 and Docker running but you can just run `mvn quarkus:dev` and see it in action.

https://github.com/melloware/quarkus-monorepo

**Comment by melloware** [comment]
let me know if you have any issues but as long as you have Docker running and JDK17 the whole thing should just work and show you and end to end example!

**Comment by melloware** [comment]
no go to localhost:8080

**Pull request merged**
