### PR TITLE
Revert "Upgrade Webpack"

### PR DESCRIPTION
**Pull request by melloware**
Reverts quarkiverse/quarkus-quinoa#329

### CODE REVIEW

**Comment by melloware** [comment]
cc @shivam-sharma7 looks like tests are failing in GitHub actions.

**Review by shivam-sharma7 — APPROVED** [review]
LGTM

**Review by shivam-sharma7 — APPROVED** [review]
LGTM

**Comment by melloware** [comment]
@shivam-sharma7 Actually all you have to do is run `npm install` so it updates package.json and submit another PR please.

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 Actually all you have to do is run `npm install` so it updates package.json and submit another PR please.

have you setup for node?

**Comment by melloware** [comment]
Yep the CI is setup but you forgot to install `package-lock.json` in your PR.  That file is needed when you update package.json.

**Comment by shivam-sharma7** [comment]
> Yep the CI is setup but you forgot to install `package-lock.json` in your PR. That file is needed when you update package.json.

you mean `npm install` inside webui dir

**Comment by melloware** [comment]
yes.

**Pull request closed without merging**
