### PR TITLE
Publish built package

### PR DESCRIPTION
**Pull request by alex-kovalenko1982**
## Describe your changes
Additional build step has been introduced to run package manager publish command. This allows to push built package to the remote registry. This is particularly handy when using together with `quarkus.quinoa.just-build` option enabled.

## Fixes Issue
PR is a follow-up of the discussion here
https://github.com/quarkiverse/quarkus-quinoa/discussions/756
 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ia3andy** [comment]
I haven't tried it but code looks good! Thanks @alex-kovalenko1982 :)

**Review by melloware — APPROVED** [review]
LGTM

**Comment by melloware** [comment]
@all-contributors add @alex-kovalenko1982 for code

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I am pushing 2.5.0 to Maven Central now.

**Pull request merged**
