### PR TITLE
Feature/UI base path

### LINKED ISSUE #299: Deal with vite application base path
Hello,

My quarkus application is running on a specific root path. Let's say /hello.
That's the same for my vite react application which has the base path set at /hello.

It looks like I cannot configure Quinoa to set this base endpoint for my application.
It removes the root path and calls the front without it anyway.

Did I miss something or I should do a PR for that?
(Working on Quarkus 2 btw)
Thanks in advance for your reply.

### PR DESCRIPTION
**Pull request by smoothdub**
Fix #299 

I have added a property to deal with a root path on the UI side.
The property is named uiBasePath and the default value is / 
Tested with the dev mode in my use case and also tested after a build, directly from the jar.

### CODE REVIEW

**Comment by ia3andy** [comment]
Have a look to this:
https://github.com/quarkiverse/quarkus-quinoa/issues/299#issuecomment-1495467230

**Comment by ia3andy** [comment]
Please make sure your use case can't be solved in the Vite app, because from what you said it seems to be the case.

Let's not make the Quinoa config more complex with something that we don't need (yet anyway).

**Comment by smoothdub** [comment]
I just get why we have so much trouble to clearly understand each other. This bug is a bug only when we use the "forward to dev server mode".  A you forward always on / , it will fails because the dev server cannot response. When the ui is compiled, it will work fine. 

I'll change the props name but I assume that quinoa.path is not correct anymore. Maybe quinoa.devserver.path ?

**Comment by smoothdub** [comment]
Moved to quinoa.dev-server.path

**Comment by ia3andy** [comment]
I've seen your PR changes and note, thanks!

There is indeed a problem, but there might be an easier fix, I'll keep you up to date on my investigation...

**Comment by ia3andy** [comment]
I've tested dev-mode and prod mode, both works fine!

**Comment by ia3andy** [comment]
Here is the example app: https://github.com/ia3andy/vite-sub-path

**Comment by ia3andy** [comment]
Ok the host bug is in vite when the host is not set to `127.0.0.1`, this also works:
```properties
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
quarkus.quinoa.package-manager-install.node-version=18.15.0
quarkus.http.root-path=/foo
```

```json
    "start": "vite --base=/foo/ --host=127.0.0.1",
    "build": "vite build --base=/foo/",
```


And this time `localhost:5173/foo/index.html` is served (vite has a few bugs it seems :))

**Comment by smoothdub** [comment]
Hi @ia3andy ,

Indeed this solution looks more convenient.
I tried it and it works fine but it looks like spa-routing does not work. Did you try on your side?

I'll continue to test it.

**Comment by ia3andy** [comment]
> Hi @ia3andy ,
> 
> Indeed this solution looks more convenient. I tried it and it works fine but it looks like spa-routing does not work. Did you try on your side?
> 
> I'll continue to test it.

I'll give a try, I haven't tested SPA routing with root-path.

**Comment by ia3andy** [comment]
@smoothdub I've tested spa-routing and it seems to work:
https://github.com/ia3andy/vite-sub-path/commit/00ea13c7401ca7ea61372dbd85c5c2dff732571a

with `quarkus dev`, I can hit http://localhost:8080/foo/some-route

**Comment by smoothdub** [comment]
@ia3andy Indeed it's working fine on your sample, even if I import my web app into it. Could it be because I'm still on Quarkus 2?

**Comment by ia3andy** [comment]
> @ia3andy Indeed it's working fine on your sample, even if I import my web app into it. Could it be because I'm still on Quarkus 2?

To try with Quarkus 2, you need:
- apply the fix on the `1.x` branch of quinoa and build
- switch to 999-SNAPSHOT for quinoa
- make sure it's resteasy-reactive (not classic)
- enable spa

**Comment by smoothdub** [comment]
@ia3andy I migrated my project to quarkus 3, still the same issue. I will continue my investigation

**Comment by ia3andy** [comment]
@smoothdub what's your config? what url exactly is not working?

**Comment by ia3andy** [comment]
> @smoothdub what's your config? what url exactly is not working?

Could you change your PR with the fix please, so we can merge this

**Comment by melloware** [comment]
> Could you change your PR with the fix please, so we can merge this. Please also rebase to 1 commit (or create a new PR)

@ia3andy you can always squash them on merge with the Squash Commit button...

image

**Pull request closed without merging**
