### PR TITLE
Center: logo and heading

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Center: logo and heading in README.md

 
 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
image

**Review by melloware — APPROVED** [review]

**Comment by shivam-sharma7** [comment]
hope @ia3andy like this change

**Comment by melloware** [comment]
I really like it centered!

**Comment by melloware** [comment]
@shivam-sharma7 I stole it for my other project 😄  https://github.com/melloware/quarkus-monorepo

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 I stole it for my other project 😄 https://github.com/melloware/quarkus-monorepo

Awesome

**Pull request merged**
