### PR TITLE
Update README.md - add a link to repository map

### PR DESCRIPTION
**Pull request by alexkarezin**
## Describe your changes

Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/quarkiversequarkusquinoa/).

Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.

In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

## Fixes Issue
Documentation-only change
 
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by melloware** [comment]
Nice let me check it out.  If I like it I will add it to some other extensions I manage

**Comment by alexkarezin** [comment]
Thanks for looking into it!
> Just testing it looks like your shield doesn't support `?style=for-the-badge` ??

Correct - it does not. Is it a requirement?

**Comment by melloware** [comment]
Well on some of my other projects I like that style like this: https://github.com/open-sce/fluent-cli

**Comment by alexkarezin** [comment]
Oh, I see! Would it be better I refer directly to shields.io? Like this: 
https://img.shields.io/badge/SourceSpy-Project_Map-blue.svg?style=for-the-badge

**Comment by melloware** [comment]
yes that would be great! so for this PR don't use `?style-for-the-badge` but yeah I like the direct shields.io URL!

**Comment by shivam-sharma7** [comment]
@alexkarezin may you squash your commits?

**Comment by melloware** [comment]
@all-contributors add @alexkarezin for docs

**Comment by alexkarezin** [comment]
> yes that would be great! so for this PR don't use `?style-for-the-badge` but yeah I like the direct shields.io URL!

Thank you for merging and adding me in!

**Pull request merged**
