### PR TITLE
let quinoa download node 18.16.0

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Describe your changes
let quinoa download node 18.16.0

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ia3andy — APPROVED** [review]
LGTM

**Comment by shivam-sharma7** [comment]
Thanks!

**Comment by shivam-sharma7** [comment]
I want to ask you that can I use the Quinoa Latest version in Quarkus 2.x project?

**Comment by ia3andy** [comment]
> I want to ask you that can I use the Quinoa Latest version in Quarkus 2.x project?

You can use the 1.x versions of Quinoa which are kept up to date with the important fixes and features

**Comment by shivam-sharma7** [comment]
Thanks for the suggestion!

**Pull request merged**
