### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by ia3andy**
@melloware go?

@fblan did you give it a try?

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Its a go from me.

**Comment by melloware** [comment]
Looks like the release failed?

**Comment by melloware** [comment]
I think 2.2.0 is not showing up as the latest version in the Maven sites because the CR's were 2.2.0.CR3 instead of 2.2.0-CR3 so it thinks that 4th dot is a more specific version in semver.

**Comment by ia3andy** [comment]
Weird Quarkus Core does the same: https://central.sonatype.com/artifact/io.quarkus/quarkus-core/versions

**Comment by ia3andy** [comment]
Looks ok:
https://central.sonatype.com/artifact/io.quarkiverse.quinoa/quarkus-quinoa/versions

**Comment by ia3andy** [comment]
image

**Comment by melloware** [comment]
OK weird an hour ago it was not updating.  Maybe a Maven Central weirdness?

**Comment by fblan** [comment]
Yep, it was working perfectly! no problems!

Le lun. 2 oct. 2023 à 17:54, Andy Damevin ***@***.***> a
écrit :

**Pull request merged**
