### PR TITLE
ESBuild builder detected with last versions of angular framework

### LINKED ISSUE #579: Angular 17 Framework Support
### Describe the bug

When I create a new quarkus app, add the quinoa extension and create an Angular 17 app in the src/main/webui folder, everything seems to work as expected regarding the application. However, when I try and build, the Angular app doesn't seem to get packaged with the application. 

### Quinoa version

2.2.1

### Quarkus version

3.6.0

### Build / Runtime

Angular

### Package Manager

NPM

### Steps to reproduce the behavior

```
quarkus create app com.snimmo:quarkus-angular-quinoa-example
cd quarkus-angular-quinoa-example
quarkus ext add config-yaml resteasy-reactive-jackson quinoa
mv src/main/resources/application.properties src/main/resources/application.yml
yq -i '.quarkus.quinoa.enable-spa-routing = true' src/main/resources/application.yml
mkdir src/main/webui
ng new --routing --style scss --directory src/main/webui -g --ssr false --standalone false example-ng
```

When I run `quarkus dev`, everything seems fine. 

When I run `quarkus build`, and then attempt to run `java -jar target/quarkus-app/quarkus-run.jar`, the Angular app is not served and the regular index.html file is served that gets generated with a new Quarkus app. 

### Expected behavior

When I run `quarkus build`, and then run `java -jar target/quarkus-app/quarkus-run.jar`, I should see the same Angular app served that I saw in `quarkus dev`

### PR DESCRIPTION
**Pull request by yatho**
## Describe your changes

I have added the check of angular builder used in the web project to check if the project use EsBuild or Webpack. With EsBuild a /browser folder was added in dist directory during the build.

## Fixes Issue
Closes #579
 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by yatho** [comment]
@ia3andy I have done the PR about Angular build path as we talked at RivieraDev. Enjoy to read your comments.

**Review by melloware — APPROVED** [review]
Thank you @yatho !  I will let @ia3andy chime in but this looks good to me.

**Comment by melloware** [comment]
@all-contributors add @yatho for code

**Review by ia3andy — APPROVED** [review]
Looking good @yatho :) 

Right @melloware ?

**Comment by melloware** [comment]
yep it looks great to me!

**Pull request merged**
