### PR TITLE
2.0.7 Release

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
@melloware Thanks #427

**Review by melloware — APPROVED** [review]

**Comment by shivam-sharma7** [comment]
@melloware I think you have access to do this think-https://github.com/quarkiverse/quarkus-quinoa/releases

**Comment by shivam-sharma7** [comment]
@melloware I think we need to provide `gpg_private_key` in workflow

**Comment by shivam-sharma7** [comment]
> We never had this before it all just worked. This is all configured by the core Quarkiverse stuff?

If you agree then let's revert #428 this reopen your and merge it #427 then will see..

**Comment by shivam-sharma7** [comment]
then wait i want to add support for another framework or we can do this in 2.0.9

**Comment by melloware** [comment]
go ahead and do it now.  I won't merge 2.0.8 yet.

**Comment by shivam-sharma7** [comment]
> go ahead and do it now. I won't merge 2.0.8 yet.

track my branch- https://github.com/quarkiverse/quarkus-quinoa/compare/main...shivam-sharma7:quarkus-quinoa:patch-2

**Comment by melloware** [comment]
Aurelia should be AURELIA

**Pull request merged**
