### PR TITLE
PackageManagerType refactor

### PR DESCRIPTION
**Pull request by melloware**
@ia3andy I was going to work on the PNPM and YARN tickets but I first thought I would refactor this to use 1 enum across everywhere as we had code all over the place for YARN, PNMP, NPM.

```java
public enum PackageManagerType {

    YARN("yarn","yarn.lock"),
    NPM("npm", "package-lock.json"),
    PNPM("pnpm", "pnpm-lock.yaml");

    private final String command;
    private final String lockFile;


    PackageManagerType(String command, String lockFile) {
        this.command = command;
        this.lockFile = lockFile;
    }

    public String getCommand() {
        return command;
    }

    public String getLockFile() {
        return lockFile;
    }
}
```

### CODE REVIEW

**Comment by ia3andy** [comment]
Hey @melloware, I am not sure it's good. to have the enum in the runtime module while there is no relation between package manager and the runtime part. IMHO it's better to have the "shared" part duplicated for testing than having this where it doesn't belong (even if this reduce a bit the quantity of code). WDYT?

**Comment by melloware** [comment]
I thought of that too the Runtime was the only lib accessible by all parts that need it.   I can duplicate it in the Deployment and Deployment Test packages but it goes against my internal DRY (Don't Repeat Yourself) principals of having to edit something in two places.   

Let me know if you definitely want to duplicate it and I will!

**Comment by ia3andy** [comment]
> I thought of that too the Runtime was the only lib accessible by all parts that need it. I can duplicate it in the Deployment and Deployment Test packages but it goes against my internal DRY (Don't Repeat Yourself) principals of having to edit something in two places.
> 
> Let me know if you definitely want to duplicate it and I will!

I guess we could have a solution in between, you could put the Enum in deployment and pass in the plain java info the deployment tests when needed, String, or Lambda, Functions or whatever (if you get what I mean). This way you don't duplicate and you keep things as simple as possible.. WDYT?

**Comment by melloware** [comment]
OK let me try that.

**Comment by melloware** [comment]
OK done... I like this better

**Review by ia3andy — APPROVED** [review]
LGTM

**Comment by ia3andy** [comment]
Neat!

**Pull request merged**
