### PR TITLE
Release 2.0.6

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by ia3andy** [comment]
I will add the new predicate based watch location before we release

**Comment by ia3andy** [comment]
@melloware unless you want to give it a shot?

**Comment by melloware** [comment]
Oh I can close this PR if you want to add that.  I looked at the Predicate based and was confused on how to make it work based on what we are doing now?

**Comment by ia3andy** [comment]
@melloware keep it open, you will just have to rebase..

**Review by ia3andy — APPROVED** [review]
LGTM

**Comment by ia3andy** [comment]
FYI, @melloware I think we should have released the framework auto-detection with a new minor 2.1.x, but it's a bit late for it, next time we should be careful because it changes the dev-mode behaviour in existing projects.

**Comment by ia3andy** [comment]
🤪

**Comment by melloware** [comment]
Should I make this 2.1.0 then?

**Pull request merged**
