### PR TITLE
2.0.9

### PR DESCRIPTION
**Pull request by shivam-sharma7**

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by shivam-sharma7** [comment]
I think we should plan for mejor or 3.x

**Comment by melloware** [comment]
Next version would be 2.1 a 3.0 would be a huge change.   We haven't really had any major changes recently according to `semantic versioning` strategy.  See: https://semver.org/

**Comment by ia3andy** [comment]
@shivam-sharma7 @melloware any reason why you are releasing that often?

**Comment by melloware** [comment]
Agreed @ia3andy we should bundle up more changes before releasing.

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 @melloware any reason why you are releasing that often?

we have two new frameworks support and complete docs as well, This will our last. Next would be 2.1.x and it will take some time.

**Comment by ia3andy** [comment]
framework support is not enough to trigger a new release, no one will use those two new framework right after the release :) and if they do they can always have custom config.

**Comment by shivam-sharma7** [comment]
> framework support is not enough to trigger a new release, no one will use those two new framework right after the release :) and if they do they can always have custom config.

okay, closing :)

**Comment by shivam-sharma7** [comment]
> framework support is not enough to trigger a new release, no one will use those two new framework right after the release :) and if they do they can always have custom config.

@ia3andy Tell me some work which need in quinoa

**Comment by ia3andy** [comment]
> > framework support is not enough to trigger a new release, no one will use those two new framework right after the release :) and if they do they can always have custom config.
> 
> @ia3andy Tell me some work which need in quinoa

I think the extension is already pretty cool, new stuff will come but they are big pieces of work.

**Pull request closed without merging**
