### PR TITLE
Vite dev server port 3000

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ia3andy** [comment]
@shivam-sharma7 why this PR?

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 why this PR?

@ia3andy I have tried to create a quinoa-app and run into my local machine, during `npm run dev` then it serving app on `port 5173` this PR will convert this on `port 3000` by default

**Comment by ia3andy** [comment]
@shivam-sharma7 but with the new framework detection, if you don't have any quinoa port setting in your application.properties, it should use the default vite port 5173 I think.

This should not be needed.

**Comment by shivam-sharma7** [comment]
@ia3andy oh, like this- https://github.com/Hyperfoil/Horreum/blob/bacb04c353527134ef72d8720e68e9d45bf7051e/horreum-backend/src/main/resources/application.properties#L109

**Comment by ia3andy** [comment]
> @ia3andy oh, like this- https://github.com/Hyperfoil/Horreum/blob/bacb04c353527134ef72d8720e68e9d45bf7051e/horreum-backend/src/main/resources/application.properties#L109

yes, if you are using the latest Quinoa, you can remove this line (with Vite)

**Pull request closed without merging**
