### PR TITLE
Fix #715: Update runtime production drawing

### LINKED ISSUE #715: Update runtime diagram to reflect recent routing changes
Now, Quinoa is not in charge of the route to serve the static files anymore, this is done by Quarkus Http. This should be reflected in the doc: https://docs.quarkiverse.io/quarkus-quinoa/dev/main-concepts.html#_runtime_for_production_mode

Source is here:
https://github.com/quarkiverse/quarkus-quinoa/blob/main/docs/modules/ROOT/assets/images/quinoa-runtime-prod.excalidraw

### PR DESCRIPTION
**Pull request by melloware**
Fix #715: Update runtime production drawing

image

### CODE REVIEW

**Comment by ia3andy** [comment]
@melloware the index.html should be returned by the static resource handler

**Comment by melloware** [comment]
OK should vert.X be removed?

**Comment by melloware** [comment]
OK how about this: 

image

**Review by ia3andy — APPROVED** [review]
Thanks 😅

**Pull request merged**
